---
# Source: oauth-proxy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauthproxy
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"oauthproxy"}}'
  labels:
    app: oauthproxy
    "app.kubernetes.io/name": oauthproxy
---
# Source: oauth-proxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: oauthproxy
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: oauthproxy-tls
  labels:
    app: oauthproxy
    app.kubernetes.io/name: oauthproxy
spec:
  type: ClusterIP
  ports:
    - port: 7443
      targetPort: 7443
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: oauthproxy
---
# Source: oauth-proxy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauthproxy
  labels:
    app: oauthproxy
    app.kubernetes.io/name: oauthproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauthproxy
  template:
    metadata:
      labels:
        app: oauthproxy
        app.kubernetes.io/name: oauthproxy
    spec:
      serviceAccountName: oauthproxy
      volumes:
        - name: proxy-tls
          secret:
            secretName: oauthproxy-tls
        - name: open-certs-volume
          configMap:
            name: openpages
      containers:
        - name: oauthproxy
          image: openshift/oauth-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7443
          args:
            - --https-address=:7443
            - --provider=openshift
            - --openshift-service-account=oauthproxy
            - --upstream=https://52.116.127.66:10111
            - --request-logging=true
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --cookie-secret=SECRET
            - --ssl-insecure-skip-verify=true
            - --upstream-ca=/etc/tls/private/ca/openpages.crt
          volumeMounts:
            - mountPath: /etc/tls/private
              name: proxy-tls
            - name: open-certs-volume
              mountPath: /etc/tls/private/ca
        - name: example
          image: "docker.io/bitnami/nginx"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
# Source: oauth-proxy/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: oauthproxy
  labels:
    app: oauthproxy
spec:
  to:
    kind: Service
    name: oauthproxy
  port:
    targetPort: 7443
  tls:
    termination: reencrypt
    certificate: |
      -----BEGIN CERTIFICATE-----
        << Insert FalconBanc PEM Contents >>
      -----END CERTIFICATE-----
    key: "-----BEGIN PRIVATE KEY-----
      << Insert FalconBanc KEy Contents>>
      -----END PRIVATE KEY-----\r\n"
    caCertificate: |
      -----BEGIN CERTIFICATE-----
        << Insert LetsEncrypt CA Contents >>
      -----END CERTIFICATE-----
