---
# Source: oauth-proxy/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauthproxy
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"oauthproxy"}}'
  labels:
    app: oauthproxy
    "app.kubernetes.io/name": oauthproxy
---
# Source: oauth-proxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: oauthproxy
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: oauthproxy-tls
  labels:
    app: oauthproxy
    app.kubernetes.io/name: oauthproxy
spec:
  type: ClusterIP
  ports:
    - port: 7443
      targetPort: 7443
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: oauthproxy
---
# Source: oauth-proxy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauthproxy
  labels:
    app: oauthproxy
    app.kubernetes.io/name: oauthproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauthproxy
  template:
    metadata:
      labels:
        app: oauthproxy
        app.kubernetes.io/name: oauthproxy
    spec:
      serviceAccountName: oauthproxy
      volumes:
        - name: proxy-tls
          secret:
            secretName: oauthproxy-tls
        - name: open-certs-volume
          configMap:
            name: openpages
      containers:
        - name: oauthproxy
          image: openshift/oauth-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7443
          args:
            - --https-address=:7443
            - --provider=openshift
            - --openshift-service-account=oauthproxy
            - --upstream=https://52.116.127.66:10111
            - --request-logging=true
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --cookie-secret=SECRET
            - --ssl-insecure-skip-verify=true
            - --upstream-ca=/etc/tls/private/ca/openpages.crt
          volumeMounts:
            - mountPath: /etc/tls/private
              name: proxy-tls
            - name: open-certs-volume
              mountPath: /etc/tls/private/ca
        - name: example
          image: "docker.io/bitnami/nginx"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
# Source: oauth-proxy/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: oauthproxy
  labels:
    app: oauthproxy
spec:
  to:
    kind: Service
    name: oauthproxy
  port:
    targetPort: 7443
  tls:
    termination: reencrypt
    certificate: |
      -----BEGIN CERTIFICATE-----
      MIIFZjCCBE6gAwIBAgISA+r6s/o26Sv0IrGsF3NA3KvJMA0GCSqGSIb3DQEBCwUA
      MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
      ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0yMDEwMjMxNTU1NTNaFw0y
      MTAxMjExNTU1NTNaMBkxFzAVBgNVBAMTDmZhbGNvbmJhbmMuY29tMIIBIjANBgkq
      hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzuBQ4KR9mx0riHB2BQXGy01K3fHlC/wX
      49GZx0GF3PzCAvvRNtilR1ZZ+yDF9RI74mfEnWtMs1C5Sx0CUOlt5WajR+KdevtC
      95PAxBEi65Cfq/OVkXKFgYKuVdD5nu2cj+lzrQ1E5Eot3O6PkMOvwjG1Hv/8VMXa
      aKRzi/Kxbf7W7JCrKfH2snTcBk+LraT1BCvWM/SLM6uZXTJlZPV3RfgLXPx4vK5J
      nwjZzhMjO2Rd0grWz1qV4N9WzxapHZVyOvdYsoYN4gp/3JvhG48EqwfLBgBa4wNT
      xhAI0eN0VrkdyR9Zphgbd5rUXB+RIkmvWz/m5urtXYIm8TYgUc/qVQIDAQABo4IC
      dTCCAnEwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEF
      BQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBQ0fTZS5699G4RzWG+XzOzBN+B9
      WjAfBgNVHSMEGDAWgBSoSmpjBH3duubRObemRWXv86jsoTBvBggrBgEFBQcBAQRj
      MGEwLgYIKwYBBQUHMAGGImh0dHA6Ly9vY3NwLmludC14My5sZXRzZW5jcnlwdC5v
      cmcwLwYIKwYBBQUHMAKGI2h0dHA6Ly9jZXJ0LmludC14My5sZXRzZW5jcnlwdC5v
      cmcvMCsGA1UdEQQkMCKCECouZmFsY29uYmFuYy5jb22CDmZhbGNvbmJhbmMuY29t
      MEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUH
      AgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBBAYKKwYBBAHWeQIEAgSB
      9QSB8gDwAHYARJRlLrDuzq/EQAfYqP4owNrmgr7YyzG1P9MzlrW2gagAAAF1VmNb
      uQAABAMARzBFAiEA40o4phkHnF4vLK7BiEGNmRhYveu4nqoDJF7QrLn5A+ICIDxr
      otG1IGipNSLnPg8rKaT+xZu2wpir0HdBbTfkafF5AHYA9lyUL9F3MCIUVBgIMJRW
      juNNExkzv98MLyALzE7xZOMAAAF1VmNbrwAABAMARzBFAiEAmFNZw9VYag5vobre
      tS2v7bTTbtjmPSanAk3C+uMzDJYCIF7wTgW3kwpFO/dUUCmj3gswVlZX2qBaJ91K
      Ijlbf61SMA0GCSqGSIb3DQEBCwUAA4IBAQBQoB3Rnqzx3Qpz8cXNdw5zWjioIW0Y
      wZ/+b1sP52jEEn7+rB5t2fHFnjihjz/QgTo2Af4FPKM8U+8AlaOotthJofjjj/1v
      LZQNPmXftVrV/cvZ6DUvbXzp2uqqi19pTa/LicNGlMz1p62vQoVxFTFoCYsPLyoI
      411ccyV2emQiPDr2bQz16UvLTKvN1BEC9WbHki9HuaffeF54ymrVwQFTH3dMram+
      EvxhM6gFPWMGEx8feX4T5i2+rb92tPQQ6LDMCH/kh3C673YAEBRXd84guqa/XALy
      qiaSvDkasymuI9YZ3ItLvMx4kxeMEqeClM+/D9ucGJmrDjlzpJwlNO8u
      -----END CERTIFICATE-----
    key: "-----BEGIN PRIVATE KEY-----\r\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDO4FDgpH2bHSuIcHYFBcbLTUrd\r\n8eUL/Bfj0ZnHQYXc/MIC+9E22KVHVln7IMX1EjviZ8Sda0yzULlLHQJQ6W3lZqNH4p16+0L3k8DE\r\nESLrkJ+r85WRcoWBgq5V0Pme7ZyP6XOtDUTkSi3c7o+Qw6/CMbUe//xUxdpopHOL8rFt/tbskKsp\r\n8faydNwGT4utpPUEK9Yz9Iszq5ldMmVk9XdF+Atc/Hi8rkmfCNnOEyM7ZF3SCtbPWpXg31bPFqkd\r\nlXI691iyhg3iCn/cm+EbjwSrB8sGAFrjA1PGEAjR43RWuR3JH1mmGBt3mtRcH5EiSa9bP+bm6u1d\r\ngibxNiBRz+pVAgMBAAECggEAb19P60Bi5qjzkMaKovWTKkv4LDhXyPX0no9urFjYCjqA8D5FSbOk\r\ndx1D3/Cq4d7pImAe92iWqEqjFo8NeiXRJhj1enPDuDugt8xxkJxxIkR/0YCXWvA+c5S46jZQzIC7\r\nMrbJsbZdClHtEu3TmGnhKzi7e27wl2rUxFUUZ5lGcCIz/lqVQ4BLjW9vRkE6WartQP7PGfUPXOUK\r\n+g4zbdjSHhy+aCH5uoRzYqMRWrTEbIZZX+AV+Diao4/Z9zH+mCYXTC0shJm2pK9WenaRCfL/0Uir\r\nsP69tznwCYJybnhDhVO0VhGYax4dJR8H8rv0dFZTnnf2EqJuhx2lrcj0Ij5QmQKBgQDuVG/uL7BA\r\nXlMeSQxpeCJXmwrww0rNu1DOlmNVfdSt2/ceBL+pI+eP/PMXK4ZwkwJDunMwkYb4rSBwIZZYsicC\r\nI73aa7FJvhZc/QB5OX54p9zIBmxqo8zc4+tc8YTqRPKB4aNxvV90WCrvFOwxE5R3C22nv5bejAIQ\r\nrIGOn5qubwKBgQDeNuGSXuml3CC4X0uw7LItaQp9U/U0o99FFlpoHmpnlZNrIBMetfGBlM21w8fH\r\n90q9KG4H9fI97pRiqF1I1/HNIzF6UQ9mErMOu5ThEOwnRTxrKlcwAuekd+3RWncbjTtmtMfippLG\r\niBROChfD9Bo09C7qBiL03/PiWY3S2EEVewKBgQDhrLDEYQHLIcYg8li/chNK0zQb4UDu6IVO6Zar\r\n+FewPY6VLTfzSF1XudTRxtQpuvq0+VNj1RlyVjVWGGfOGvvXCdMXhUw+ILH6YVPWdjussn7cJUD6\r\nBZrSOzu+KbCLSLg9hlSHOiOt/mLBOxWgLwMxam/uHPwWRYsbEM4pKDaHHwKBgQDP0U22oRMsbakg\r\nJOdZ6JNeSq1ntlxNRbCqIRSd6Uwj4cxD1HRtNUVOpcaY5idyCQEZ1LTKtyY862JUvha36FUYP4Cn\r\nXyXilTxmW+IJdtUUiPjPVILDwQO4WfzM3SklWDkkfY+ulZARIfSzY1cEiMb1nSQ+80w/7S5eEtjD\r\nRkHf/wKBgHu3oH0hP4cZjH59n5QRM5D82Z7qmDhmUvaLurm6lAoLMCTTOR7iI7LYv0Z8aDw1zJIo\r\n7BZtHAY9+PA1HLlusqGWElqVIksQzVPdvTelZc2ZdWI1HXYPXA3Hm1DxyMqI9M0H+DbNcWvPiP0Z\r\nE3KHiH5TLq/fZfZlfdBHt7LUPq5W\r\n-----END PRIVATE KEY-----\r\n"
    caCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIFjTCCA3WgAwIBAgIRANOxciY0IzLc9AUoUSrsnGowDQYJKoZIhvcNAQELBQAw
      TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
      cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTYxMDA2MTU0MzU1
      WhcNMjExMDA2MTU0MzU1WjBKMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
      RW5jcnlwdDEjMCEGA1UEAxMaTGV0J3MgRW5jcnlwdCBBdXRob3JpdHkgWDMwggEi
      MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCc0wzwWuUuR7dyXTeDs2hjMOrX
      NSYZJeG9vjXxcJIvt7hLQQWrqZ41CFjssSrEaIcLo+N15Obzp2JxunmBYB/XkZqf
      89B4Z3HIaQ6Vkc/+5pnpYDxIzH7KTXcSJJ1HG1rrueweNwAcnKx7pwXqzkrrvUHl
      Npi5y/1tPJZo3yMqQpAMhnRnyH+lmrhSYRQTP2XpgofL2/oOVvaGifOFP5eGr7Dc
      Gu9rDZUWfcQroGWymQQ2dYBrrErzG5BJeC+ilk8qICUpBMZ0wNAxzY8xOJUWuqgz
      uEPxsR/DMH+ieTETPS02+OP88jNquTkxxa/EjQ0dZBYzqvqEKbbUC8DYfcOTAgMB
      AAGjggFnMIIBYzAOBgNVHQ8BAf8EBAMCAYYwEgYDVR0TAQH/BAgwBgEB/wIBADBU
      BgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEBATAwMC4GCCsGAQUFBwIB
      FiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQub3JnMB0GA1UdDgQWBBSo
      SmpjBH3duubRObemRWXv86jsoTAzBgNVHR8ELDAqMCigJqAkhiJodHRwOi8vY3Js
      LnJvb3QteDEubGV0c2VuY3J5cHQub3JnMHIGCCsGAQUFBwEBBGYwZDAwBggrBgEF
      BQcwAYYkaHR0cDovL29jc3Aucm9vdC14MS5sZXRzZW5jcnlwdC5vcmcvMDAGCCsG
      AQUFBzAChiRodHRwOi8vY2VydC5yb290LXgxLmxldHNlbmNyeXB0Lm9yZy8wHwYD
      VR0jBBgwFoAUebRZ5nu25eQBc4AIiMgaWPbpm24wDQYJKoZIhvcNAQELBQADggIB
      ABnPdSA0LTqmRf/Q1eaM2jLonG4bQdEnqOJQ8nCqxOeTRrToEKtwT++36gTSlBGx
      A/5dut82jJQ2jxN8RI8L9QFXrWi4xXnA2EqA10yjHiR6H9cj6MFiOnb5In1eWsRM
      UM2v3e9tNsCAgBukPHAg1lQh07rvFKm/Bz9BCjaxorALINUfZ9DD64j2igLIxle2
      DPxW8dI/F2loHMjXZjqG8RkqZUdoxtID5+90FgsGIfkMpqgRS05f4zPbCEHqCXl1
      eO5HyELTgcVlLXXQDgAWnRzut1hFJeczY1tjQQno6f6s+nMydLN26WuU4s3UYvOu
      OsUxRlJu7TSRHqDC3lSE5XggVkzdaPkuKGQbGpny+01/47hfXXNB7HntWNZ6N2Vw
      p7G6OfY+YQrZwIaQmhrIqJZuigsrbe3W+gdn5ykE9+Ky0VgVUsfxo52mwFYs1JKY
      2PGDuWx8M6DlS6qQkvHaRUo0FMd8TsSlbF0/v965qGFKhSDeQoMpYnwcmQilRh/0
      ayLThlHLN81gSkJjVrPI0Y8xCVPB4twb1PFUd2fPM3sA1tJ83sZ5v8vgFv2yofKR
      PB0t6JzUA81mSqM3kxl5e+IZwhYAyO0OTg3/fs8HqGTNKd9BqoUwSRBzp06JMg5b
      rUCGwbCUDI0mxadJ3Bz4WxR6fyNpBK2yAinWEsikxqEt
      -----END CERTIFICATE-----
