apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ldap-port
      protocol: TCP
      port: {{ .Values.service.ldapPort }}
      targetPort: {{ .Values.service.ldapPort }}
    - name: ssl-ldap-port
      protocol: TCP
      port: {{ .Values.service.sslLdapPort }}
      targetPort: {{ .Values.service.sslLdapPort }}
  selector:
    {{- include "openldap.selectorLabels" . | nindent 4 }}
    
