apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oauth-proxy.fullname" . }}
  labels:
    {{- include "oauth-proxy.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "oauth-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oauth-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oauth-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: proxy-tls
          secret:
            secretName: {{ .Values.host }}-tls
      containers:
        - name: nginx-hello
          image: docker.io/bitnami/nginx
          ports:
            - containerPort: 8080
              protocol: TCP
        - name: {{ .Chart.Name }}
          image: openshift/oauth-proxy:latest
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7443
              protocol: TCP
          args:
            - --https-address=:7443
            - --provider=openshift
            - --openshift-service-account={{ include "oauth-proxy.serviceAccountName" . }}
            - --upstream=http://localhost:8080
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --cookie-secret=SECRET
            - --request-logging=true

          volumeMounts:
            - mountPath: /etc/tls/private
              name: proxy-tls
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
