{{- $chartName := include "oauth-proxy.name" . | quote }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oauth-proxy.name" . }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":{{ .Values.host | quote }}}}'
  labels:
    app: {{ include "oauth-proxy.name" . }}
    "app.kubernetes.io/name": {{ include "oauth-proxy.name" . }}
    "helm.sh/chart": {{ include "oauth-proxy.chart" . }}
