apiVersion: v1
kind: Service
metadata:
  name: {{ include "ldapconsole.fullname" . }}
  labels:
    {{- include "ldapconsole.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: ldap-port
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: ssl-ldap-port
      protocol: TCP
      port: {{ .Values.service.sslPort }}
      targetPort: {{ .Values.service.sslPort }}
  selector:
    {{- include "ldapconsole.selectorLabels" . | nindent 4 }}
