---
# Source: oauthproxy/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauthproxy
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"oauthproxy"}}'
  labels:
    app: oauthproxy
    "app.kubernetes.io/name": oauthproxy
---
# Source: oauthproxy/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: oauthproxy
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: dashboard-tls
  labels:
    app: oauthproxy
    "app.kubernetes.io/name": oauthproxy
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: proxy
  selector:
    app: oauthproxy
---
# Source: oauthproxy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauthproxy
  labels:
    app: oauthproxy
    "app.kubernetes.io/name": oauthproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauthproxy
  template:
    metadata:
      labels:
        app: oauthproxy
        "app.kubernetes.io/name": oauthproxy
    spec:
      serviceAccountName: oauthproxy
      volumes:
        - name: proxy-tls
          secret:
            secretName: dashboard-tls
      containers:
        - name: oauth-proxy
          image: openshift/oauth-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
              name: public
          args:
            - --https-address=:8443
            - --provider=openshift
            - --openshift-service-account=oauthproxy
            - --upstream=http://localhost:8080
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --cookie-secret=SECRET
          volumeMounts:
            - mountPath: /etc/tls/private
              name: proxy-tls
        - name: oauthproxy
          image: "docker.io/bitnami/nginx"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
# Source: oauthproxy/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: oauthproxy
  labels:
    app: oauthproxy
spec:
  port:
    targetPort: proxy
  to:
    kind: Service
    name: oauthproxy
  tls:
    termination: reencrypt